export const FALLBACK_VERSES = [
  { texto: 'Porque Deus tanto amou o mundo que deu o seu Filho Unigênito, para que todo o que nele crer não pereça, mas tenha a vida eterna.', referencia: 'João 3:16' },
  { texto: 'O Senhor é o meu pastor; nada me faltará.', referencia: 'Salmos 23:1' },
  { texto: 'Tudo posso naquele que me fortalece.', referencia: 'Filipenses 4:13' },
  { texto: 'Confia no Senhor de todo o teu coração e não te estribes no teu próprio entendimento.', referencia: 'Provérbios 3:5' },
  { texto: 'Eu sou o caminho, a verdade e a vida. Ninguém vem ao Pai senão por mim.', referencia: 'João 14:6' },
  { texto: 'Buscai primeiro o Reino de Deus e a sua justiça, e todas estas coisas vos serão acrescentadas.', referencia: 'Mateus 6:33' },
  { texto: 'Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos aliviarei.', referencia: 'Mateus 11:28' },
  { texto: 'Não temas, porque eu sou contigo; não te assombres, porque eu sou o teu Deus.', referencia: 'Isaías 41:10' },
  { texto: 'O amor é paciente, o amor é bondoso. Não inveja, não se vangloria, não se orgulha.', referencia: '1 Coríntios 13:4' },
  { texto: 'Pois eu bem sei os planos que tenho para vós, diz o Senhor; planos de paz e não de mal, para vos dar o fim que desejais.', referencia: 'Jeremias 29:11' },
  { texto: 'Alegrai-vos sempre no Senhor; outra vez digo: alegrai-vos!', referencia: 'Filipenses 4:4' },
  { texto: 'Deus é o nosso refúgio e fortaleza, socorro bem presente na angústia.', referencia: 'Salmos 46:1' },
  { texto: 'Lâmpada para os meus pés é a tua palavra, e luz para o meu caminho.', referencia: 'Salmos 119:105' },
  { texto: 'Mas os que esperam no Senhor renovarão as suas forças; subirão com asas como águias.', referencia: 'Isaías 40:31' },
  { texto: 'Não vos conformeis com este mundo, mas transformai-vos pela renovação da vossa mente.', referencia: 'Romanos 12:2' },
  { texto: 'Sede fortes e corajosos. Não temais, nem vos espanteis, porque o Senhor, vosso Deus, é convosco por onde quer que andeis.', referencia: 'Josué 1:9' },
  { texto: 'Eu vim para que tenham vida e a tenham em abundância.', referencia: 'João 10:10' },
  { texto: 'O Senhor é a minha luz e a minha salvação; de quem terei medo?', referencia: 'Salmos 27:1' },
  { texto: 'A fé é a certeza das coisas que se esperam, a convicção dos fatos que não se veem.', referencia: 'Hebreus 11:1' },
  { texto: 'Eis que estou à porta e bato; se alguém ouvir a minha voz e abrir a porta, entrarei e cearei com ele, e ele comigo.', referencia: 'Apocalipse 3:20' },
  { texto: 'Em todo tempo ama o amigo; e na angústia nasce o irmão.', referencia: 'Provérbios 17:17' },
  { texto: 'E conhecereis a verdade, e a verdade vos libertará.', referencia: 'João 8:32' },
  { texto: 'Não se turbe o vosso coração; credes em Deus, crede também em mim.', referencia: 'João 14:1' },
  { texto: 'Sabemos que todas as coisas concorrem para o bem daqueles que amam a Deus.', referencia: 'Romanos 8:28' },
  { texto: 'A graça do Senhor Jesus Cristo seja com todos vós. Amém.', referencia: 'Apocalipse 22:21' },
];
